name: 'hasura-graphql-allowlist-registrar'
description: 'Extracts GraphQL files in a repository and registers them into hasura server'
inputs:
  host:
    description: 'Hasura server host'
    required: true
    default: 'http://hasura-server:8081'
  key:
    description: 'Hasura admin key'
    required: true
    default: ''
  path:
    description: 'glob path to find graphql files'
    required: false
    default: ''
outputs:
  time:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
