name: Yaml file Lint

on: [push, pull_request]

jobs:
  lint-yaml-files:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v1
      with:
        config_file: .yamllint.yml
